# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/cesar/Documentos/Tpfinal-Arquitectura/Repositorios/tpFinalArq/tp_final_arquitectura/tp_final_arquitectura.srcs/sources_1/ip/instruction_memory/instruction_memory.xci
# IP: The module: 'instruction_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cesar/Documentos/Tpfinal-Arquitectura/Repositorios/tpFinalArq/tp_final_arquitectura/tp_final_arquitectura.srcs/sources_1/ip/instruction_memory/instruction_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instruction_memory'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/cesar/Documentos/Tpfinal-Arquitectura/Repositorios/tpFinalArq/tp_final_arquitectura/tp_final_arquitectura.srcs/sources_1/ip/instruction_memory/instruction_memory.xci
# IP: The module: 'instruction_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cesar/Documentos/Tpfinal-Arquitectura/Repositorios/tpFinalArq/tp_final_arquitectura/tp_final_arquitectura.srcs/sources_1/ip/instruction_memory/instruction_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instruction_memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
